version: "3.8"
services:
  web:
    build: .
    volumes:
      # - ./golang:/root
      - ./web:/root
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    links:
      - db
    # networks:
    #   - back-tier
  db:
    image: postgres:12.3-alpine
    # image: postgres:latest
    environment:
      # POSTGRES_PASSWORD: "postgres_docker"
      # POSTGRES_DB: "postgres"
      # POSTGRES_USER: "postgres"
      # POSTGRES_HOST: "0.0.0.0"
      # POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data

    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    # networks:
    #   - back-tier
    # image: postgres:latest
    # restart: always
    # volumes:
    # - data:/var/lib/postgresql/data
    # ports:
    #   - “5433:5432”
    # expose:
    #   - "5433"
volumes:
  postgres_data:
# networks:
#   front-tier:
#   back-tier:
